name: Playbook Validation

on: [pull_request]

jobs:
  validate_playbook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch all branches
      run: |
        git fetch --all


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install -r .github/tests/requirements.txt

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Run Robot Framework tests
      run: |
        mkdir -p results
        python .github/tests/run_on_changed_playbooks.py --current-branch=origin/${{github.event.pull_request.head.ref}} --base-branch=origin/${{github.event.pull_request.base.ref}} --robot-path=.github/tests/robot/PlaybookScanner.robot

    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: results