name: Playbook Validation

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install -r .github/tests/requirements.txt

    - name: Run Robot Framework tests
      run: |
        mkdir -p results
        python .github/tests/run_on_changed_playbooks.py 6.3 .github/tests/robot/PlaybookScanner.robot

    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: robot-results
        path: results